version: '3.7'

services:

  kauricurrencyexplorer_api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "kauricurrencyexplorer_api:dev"
    container_name: kauricurrencyexplorer_api
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - "${PORT:-8002}:8002"
    expose:
      - "8002"
    command: "uvicorn currencyexplorer.main:app --host 0.0.0.0 --port 8002 --reload"
    restart: on-failure